# Generated by Django 5.2 on 2025-04-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='questions',
            name='correct',
            field=models.CharField(default=' ', max_length=256, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='questions',
            name='describe',
            field=models.TextField(blank=True, verbose_name='Развернутый ответ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(blank=True, max_length=256, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(max_length=256, verbose_name='Вопрос'),
        ),
    ]
