# Generated by Django 5.2 on 2025-04-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_category_options_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ответ'),
        ),
    ]
