# Generated by Django 5.2 on 2025-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='picture',
            field=models.ImageField(blank=True, upload_to='questions', verbose_name='Фотография'),
        ),
    ]
